name: reporting
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  usage: ^4.1.1
  tool_base:
    git: https://github.com/claudius-kienle/tool_base.git
#  tool_base:
#    path: ../tool_base
dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  mockito: ^5.4.4
  tool_base_test:
    git: https://github.com/claudius-kienle/tool_base_test.git
#    path: ../tool_base_test
  args: ^2.5.0
  quiver: ^3.2.1
  meta: ^1.1.8